name: Frontend CI

on:
  push:
    branches: ["main"]
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-ci.yml"

  pull_request:
    branches: ["main"]
    paths:
      - "frontend/**"

jobs:
  frontend-ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2️⃣ Setup Node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3️⃣ Install dependencies
      - name: Install Dependencies
        run: npm install

      # 4️⃣ Run ESLint
      - name: Run Lint
        run: npm run lint

      # 5️⃣ Build Project
      - name: Build Frontend
        run: npm run build
